version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - /home/ubuntu/csvserver/solution/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - csvserver
  csvserver:
    image: "infracloudio/csvserver:latest"
    container_name: csvserver_container
    ports:
      - 9393:9300
    volumes:
      - /home/ubuntu/csvserver/solution/inputFile:/csvserver/inputdata
    environment:
     - CSVSERVER_BORDER=Orange
